import '../models/tile_product.dart';

/// Centralized repository of all available catalog products for tiles and adhesives
class ProductCatalogService {
  static final List<TileProduct> allCatalogProducts = [
    // 1200x1800 mm Jumbo Grand Slabs
    TileProduct(
      id: 'PROD_1218_01',
      name: 'Golden Book Match Jumbo Slab',
      size: '1200x1800 mm',
      surface: 'Glossy',
      color: 'Beige - Brown',
      baseColour: 'Beige - Brown',
      pattern: 'Book Match',
      basePrice: 220.0,
      moq: 20,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Glossy',
      thickness: '9 mm',
      thicknessMm: 9.0,
      boxWeightKg: 42.0,
      productType: 'Vitrified',
      tileCategory: 'Slab Tiles',
      collection: 'Book Match',
      spaces: ['Living Room'],
      shape: 'rectangle',
      aspectRatio: '0.667',
      aspectRatioValue: 0.667,
    ),
    TileProduct(
      id: 'PROD_1218_02',
      name: 'Statuario Inky Colors Grand Slab',
      size: '1200x1800 mm',
      surface: 'Inky Colors',
      color: 'White',
      baseColour: 'White',
      pattern: 'Gold Vein',
      basePrice: 240.0,
      moq: 15,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Inky Colors',
      thickness: '9 mm',
      thicknessMm: 9.0,
      boxWeightKg: 42.0,
      productType: 'Vitrified',
      tileCategory: 'Slab Tiles',
      collection: 'Endless',
      spaces: ['Living Room'],
      shape: 'rectangle',
      aspectRatio: '0.667',
      aspectRatioValue: 0.667,
    ),
    TileProduct(
      id: 'PROD_1218_03',
      name: 'Onyx Pastel Rose Grand Slab',
      size: '1200x1800 mm',
      surface: 'Pastel Colors',
      color: 'White',
      baseColour: 'White',
      pattern: 'Onyx Soft',
      basePrice: 250.0,
      moq: 15,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Pastel Colors',
      thickness: '9 mm',
      thicknessMm: 9.0,
      boxWeightKg: 42.0,
      productType: 'Vitrified',
      tileCategory: 'Slab Tiles',
      collection: 'Golden',
      spaces: ['Living Room', 'Bedroom'],
      shape: 'rectangle',
      aspectRatio: '0.667',
      aspectRatioValue: 0.667,
    ),

    // 800x1600 mm Large Luxury Slabs
    TileProduct(
      id: 'PROD_8016_01',
      name: 'Armani Bronze Luxury Slab',
      size: '800x1600 mm',
      surface: 'Glossy',
      color: 'Beige - Brown',
      baseColour: 'Beige - Brown',
      pattern: 'Bronze Marble',
      basePrice: 175.0,
      moq: 25,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Glossy',
      thickness: '9 mm',
      thicknessMm: 9.0,
      boxWeightKg: 34.0,
      productType: 'Vitrified',
      tileCategory: 'Slab Tiles',
      collection: 'Marbles',
      spaces: ['Living Room', 'Bedroom'],
      shape: 'rectangle',
      aspectRatio: '0.5',
      aspectRatioValue: 0.5,
    ),
    TileProduct(
      id: 'PROD_8016_02',
      name: 'Pietra Grey Satin Slab',
      size: '800x1600 mm',
      surface: 'Satin Matt',
      color: 'Bianco - Grey',
      baseColour: 'Bianco - Grey',
      pattern: 'Pietra Vein',
      basePrice: 165.0,
      moq: 30,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Satin Matt',
      thickness: '9 mm',
      thicknessMm: 9.0,
      boxWeightKg: 34.0,
      productType: 'Vitrified',
      tileCategory: 'Slab Tiles',
      collection: 'Endless',
      spaces: ['Living Room'],
      shape: 'rectangle',
      aspectRatio: '0.5',
      aspectRatioValue: 0.5,
    ),
    TileProduct(
      id: 'PROD_8016_03',
      name: 'Carrara Sugar Lapato Luxury',
      size: '800x1600 mm',
      surface: 'Sugar Lapato',
      color: 'White',
      baseColour: 'White',
      pattern: 'Sugar Sparkle',
      basePrice: 185.0,
      moq: 20,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Sugar Lapato',
      thickness: '9 mm',
      thicknessMm: 9.0,
      boxWeightKg: 34.0,
      productType: 'Vitrified',
      tileCategory: 'Slab Tiles',
      collection: 'Marbles',
      spaces: ['Living Room'],
      shape: 'rectangle',
      aspectRatio: '0.5',
      aspectRatioValue: 0.5,
    ),

    // 600x1200 mm Standard Vertical Slabs
    TileProduct(
      id: 'PROD_6012_01',
      name: 'Statuario Marble Vitrified',
      size: '600x1200 mm',
      surface: 'Glossy',
      color: 'White',
      baseColour: 'White',
      pattern: 'Marble',
      basePrice: 145.0,
      moq: 30,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Glossy',
      thickness: '9 mm',
      thicknessMm: 9.0,
      boxWeightKg: 28.0,
      productType: 'Vitrified',
      tileCategory: 'Floor Tiles',
      collection: 'Marbles',
      spaces: ['Living Room', 'Bath Room'],
      shape: 'rectangle',
      aspectRatio: '0.5',
      aspectRatioValue: 0.5,
    ),
    TileProduct(
      id: 'PROD_6012_02',
      name: 'Onyx Crystal Carving',
      size: '600x1200 mm',
      surface: 'Matt - Carving',
      color: 'Beige - Brown',
      baseColour: 'Beige - Brown',
      pattern: 'Carving Vein',
      basePrice: 155.0,
      moq: 30,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Matt - Carving',
      thickness: '9 mm',
      thicknessMm: 9.0,
      boxWeightKg: 28.0,
      productType: 'Vitrified',
      tileCategory: 'Floor Tiles',
      collection: 'Golden',
      spaces: ['Living Room'],
      shape: 'rectangle',
      aspectRatio: '0.5',
      aspectRatioValue: 0.5,
    ),
    TileProduct(
      id: 'PROD_6012_03',
      name: 'Royal Botticino High Gloss',
      size: '600x1200 mm',
      surface: 'High Gloss',
      color: 'Beige - Brown',
      baseColour: 'Beige - Brown',
      pattern: 'Classic Italian',
      basePrice: 150.0,
      moq: 30,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'High Gloss',
      thickness: '9 mm',
      thicknessMm: 9.0,
      boxWeightKg: 28.0,
      productType: 'Vitrified',
      tileCategory: 'Floor Tiles',
      collection: 'Endless',
      spaces: ['Living Room', 'Bedroom'],
      shape: 'rectangle',
      aspectRatio: '0.5',
      aspectRatioValue: 0.5,
    ),
    TileProduct(
      id: 'PROD_6012_04',
      name: 'Nordic Wood Rustic Planks',
      size: '600x1200 mm',
      surface: 'Rustic Wood',
      color: 'Beige - Brown',
      baseColour: 'Beige - Brown',
      pattern: 'Timber Grain',
      basePrice: 140.0,
      moq: 40,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Rustic Wood',
      thickness: '9 mm',
      thicknessMm: 9.0,
      boxWeightKg: 28.0,
      productType: 'Vitrified',
      tileCategory: 'Floor Tiles',
      collection: '3D',
      spaces: ['Outdoor', 'Bedroom'],
      shape: 'rectangle',
      aspectRatio: '0.5',
      aspectRatioValue: 0.5,
    ),
    TileProduct(
      id: 'PROD_6012_05',
      name: 'Concrete Texture Matt Punch',
      size: '600x1200 mm',
      surface: 'Matt Punch',
      color: 'Bianco - Grey',
      baseColour: 'Bianco - Grey',
      pattern: 'Industrial Concrete',
      basePrice: 148.0,
      moq: 35,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Matt Punch',
      thickness: '9 mm',
      thicknessMm: 9.0,
      boxWeightKg: 28.0,
      productType: 'Vitrified',
      tileCategory: 'Floor Tiles',
      collection: '3D',
      spaces: ['Living Room', 'Outdoor'],
      shape: 'rectangle',
      aspectRatio: '0.5',
      aspectRatioValue: 0.5,
    ),

    // 600x600 mm Square Formats
    TileProduct(
      id: 'PROD_6060_01',
      name: 'Breccia Beige Vitrified',
      size: '600x600 mm',
      surface: 'Glossy',
      color: 'Beige - Brown',
      baseColour: 'Beige - Brown',
      pattern: 'Breccia',
      basePrice: 95.0,
      moq: 50,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Glossy',
      thickness: '8.5 mm',
      thicknessMm: 8.5,
      boxWeightKg: 26.0,
      productType: 'Vitrified',
      tileCategory: 'Floor Tiles',
      collection: 'Marbles',
      spaces: ['Living Room', 'Bath Room'],
      shape: 'square',
      aspectRatio: '1.0',
      aspectRatioValue: 1.0,
    ),
    TileProduct(
      id: 'PROD_6060_02',
      name: 'Granite Grey Anti-Skid',
      size: '600x600 mm',
      surface: 'Anti - Skid',
      color: 'Bianco - Grey',
      baseColour: 'Bianco - Grey',
      pattern: 'Grip Texture',
      basePrice: 88.0,
      moq: 50,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Anti - Skid',
      thickness: '8.5 mm',
      thicknessMm: 8.5,
      boxWeightKg: 26.0,
      productType: 'Ceramic',
      tileCategory: 'Floor Tiles',
      collection: '3D',
      spaces: ['Bath Room', 'Outdoor'],
      shape: 'square',
      aspectRatio: '1.0',
      aspectRatioValue: 1.0,
    ),
    TileProduct(
      id: 'PROD_6060_03',
      name: 'Pearl Grey Sugar Lapato',
      size: '600x600 mm',
      surface: 'Sugar Lapato',
      color: 'Bianco - Grey',
      baseColour: 'Bianco - Grey',
      pattern: 'Sugar Sparkle',
      basePrice: 110.0,
      moq: 40,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Sugar Lapato',
      thickness: '8.5 mm',
      thicknessMm: 8.5,
      boxWeightKg: 26.0,
      productType: 'Vitrified',
      tileCategory: 'Floor Tiles',
      collection: 'Endless',
      spaces: ['Living Room', 'Bedroom'],
      shape: 'square',
      aspectRatio: '1.0',
      aspectRatioValue: 1.0,
    ),

    // 600x800 mm Medium Vertical Format
    TileProduct(
      id: 'PROD_6080_01',
      name: 'Venato White Matt Punch',
      size: '600x800 mm',
      surface: 'Matt Punch',
      color: 'White',
      baseColour: 'White',
      pattern: 'Venato Vein',
      basePrice: 125.0,
      moq: 40,
      stockStatus: 'available_now',
      images: [
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
      ],
      finish: 'Matt Punch',
      thickness: '8.8 mm',
      thicknessMm: 8.8,
      boxWeightKg: 27.0,
      productType: 'Vitrified',
      tileCategory: 'Wall Tiles',
      collection: 'Wall Decore',
      spaces: ['Bath Room'],
      shape: 'rectangle',
      aspectRatio: '0.75',
      aspectRatioValue: 0.75,
    ),
  ];
}
