// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3JVKMjjcZAl6_UkTxIhR7Mi2AbObzuLQ',
    appId: '1:889001862943:web:7c9c09c666f0d4cf55f22a',
    messagingSenderId: '889001862943',
    projectId: 'itacon-app',
    authDomain: 'itacon-app.firebaseapp.com',
    storageBucket: 'itacon-app.firebasestorage.app',
    measurementId: 'G-0G58TV66PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7DbQq8iOO47Krl5m2BkYyv0vs4iybijo',
    appId: '1:889001862943:android:94550525d95604b255f22a',
    messagingSenderId: '889001862943',
    projectId: 'itacon-app',
    storageBucket: 'itacon-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5GAtHEI0GoXBRjzZBE_p8OqAdAPjI-J0',
    appId: '1:889001862943:ios:4b7ab704ac8dccc355f22a',
    messagingSenderId: '889001862943',
    projectId: 'itacon-app',
    storageBucket: 'itacon-app.firebasestorage.app',
    iosBundleId: 'com.example.itaconApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5GAtHEI0GoXBRjzZBE_p8OqAdAPjI-J0',
    appId: '1:889001862943:ios:4b7ab704ac8dccc355f22a',
    messagingSenderId: '889001862943',
    projectId: 'itacon-app',
    storageBucket: 'itacon-app.firebasestorage.app',
    iosBundleId: 'com.example.itaconApp',
  );
}
