import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import '../theme/app_theme.dart';
import '../models/tile_order.dart';
import '../services/firestore_service.dart';
import '../services/app_state_service.dart';

class OrderDetailsScreen extends StatefulWidget {
  final String orderId;
  final TileOrder? initialOrder;

  const OrderDetailsScreen({
    super.key,
    required this.orderId,
    this.initialOrder,
  });

  @override
  State<OrderDetailsScreen> createState() => _OrderDetailsScreenState();
}

class _OrderDetailsScreenState extends State<OrderDetailsScreen> {
  bool _isConfirmed = false;
  bool _isSubmitting = false;

  Future<void> _handleConfirmOrder(TileOrder order) async {
    if (!_isConfirmed || _isSubmitting) return;

    setState(() => _isSubmitting = true);
    try {
      final userId = AppStateService.instance.currentUserProfile.userId;
      await FirestoreService.instance.confirmOrder(
        orderId: order.id,
        userId: userId,
      );

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('🎉 Purchase Order Confirmed! PDF generation in progress...'),
            backgroundColor: AppTheme.statusSuccess,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to confirm order: $e'),
            backgroundColor: AppTheme.statusError,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  Future<void> _handleRejectOrder(TileOrder order) async {
    if (_isSubmitting) return;

    setState(() => _isSubmitting = true);
    try {
      final userId = AppStateService.instance.currentUserProfile.userId;
      await FirestoreService.instance.rejectOrder(
        orderId: order.id,
        userId: userId,
        reason: 'Customer declined quotation via Order Details screen.',
      );

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Quotation estimate declined.'),
            backgroundColor: AppTheme.statusError,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to reject order: $e'),
            backgroundColor: AppTheme.statusError,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  Future<void> _handleDownloadPdf(String pdfUrl) async {
    if (pdfUrl.isNotEmpty) {
      final uri = Uri.parse(pdfUrl);
      if (await canLaunchUrl(uri)) {
        await launchUrl(uri, mode: LaunchMode.externalApplication);
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Unable to open PDF URL.')),
          );
        }
      }
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('PDF is being generated by factory system. Please check back in a few seconds...'),
          backgroundColor: AppTheme.accentOrange,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<TileOrder?>(
      stream: FirestoreService.instance.getOrderStream(widget.orderId),
      initialData: widget.initialOrder,
      builder: (context, snapshot) {
        final order = snapshot.data ?? widget.initialOrder;

        if (snapshot.connectionState == ConnectionState.waiting && order == null) {
          return Scaffold(
            appBar: AppBar(title: const Text('Order Details')),
            body: const Center(child: CircularProgressIndicator(color: AppTheme.primaryNavy)),
          );
        }

        if (order == null) {
          return Scaffold(
            appBar: AppBar(title: const Text('Order Details')),
            body: const Center(child: Text('Order document not found.')),
          );
        }

        final bool isPendingRate = order.status == 'pending_rate';
        final bool isRateQuoted = order.status == 'rate_quoted';
        final bool isConfirmed = order.status == 'confirmed';
        final bool isRejected = order.status == 'rejected';

        return Scaffold(
          backgroundColor: AppTheme.backgroundColor,
          appBar: AppBar(
            title: Text('PO Details (${order.orderReference})'),
            elevation: 0,
          ),
          body: SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Top Status Alert Banner
                _buildStatusBanner(order, isPendingRate, isRateQuoted, isConfirmed, isRejected),
                const SizedBox(height: 16),

                // Order Summary Header Card
                _buildHeaderCard(order),
                const SizedBox(height: 16),

                // Ordered Items Breakdown Table
                const Text(
                  'Ordered Items Breakdown',
                  style: TextStyle(
                    fontSize: 15,
                    fontWeight: FontWeight.bold,
                    color: AppTheme.textDark,
                  ),
                ),
                const SizedBox(height: 8),
                _buildItemsTable(order, isPendingRate),
                const SizedBox(height: 16),

                // Financial Summary Card (Excluding Freight)
                if (!isPendingRate) ...[
                  _buildFinancialSummaryCard(order),
                  const SizedBox(height: 20),
                ],

                // Dynamic Action Block at Bottom
                _buildDynamicActionBlock(order, isPendingRate, isRateQuoted, isConfirmed, isRejected),
              ],
            ),
          ),
        );
      },
    );
  }

  Widget _buildStatusBanner(
    TileOrder order,
    bool isPendingRate,
    bool isRateQuoted,
    bool isConfirmed,
    bool isRejected,
  ) {
    Color bannerBg = AppTheme.primaryNavy.withValues(alpha: 0.1);
    Color bannerBorder = AppTheme.primaryNavy;
    IconData bannerIcon = Icons.hourglass_top_rounded;
    String bannerTitle = 'Rate Approval in Progress';
    String bannerDesc = 'Your assigned salesperson is currently quoting today\'s factory rates.';

    if (isRateQuoted) {
      bannerBg = AppTheme.accentOrange.withValues(alpha: 0.12);
      bannerBorder = AppTheme.accentOrange;
      bannerIcon = Icons.mark_email_unread_rounded;
      bannerTitle = "Today's Quoted Rates Received";
      bannerDesc = 'Please review today\'s quoted rates and confirm to finalize your Purchase Order.';
    } else if (isConfirmed) {
      bannerBg = AppTheme.statusSuccess.withValues(alpha: 0.12);
      bannerBorder = AppTheme.statusSuccess;
      bannerIcon = Icons.verified_rounded;
      bannerTitle = 'Order Confirmed';
      bannerDesc = 'Your Purchase Order has been confirmed and sent to factory production.';
    } else if (isRejected) {
      bannerBg = AppTheme.statusError.withValues(alpha: 0.12);
      bannerBorder = AppTheme.statusError;
      bannerIcon = Icons.cancel_rounded;
      bannerTitle = 'Quotation Estimate Declined';
      bannerDesc = 'You have declined today\'s quoted rates for this Purchase Order.';
    }

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: bannerBg,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: bannerBorder, width: 1),
      ),
      child: Row(
        children: [
          Icon(bannerIcon, color: bannerBorder, size: 28),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  bannerTitle,
                  style: TextStyle(
                    fontSize: 15,
                    fontWeight: FontWeight.bold,
                    color: bannerBorder,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  bannerDesc,
                  style: const TextStyle(fontSize: 12, color: AppTheme.textSubtle),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildHeaderCard(TileOrder order) {
    final createdDateStr = order.createdAt != null
        ? '${order.createdAt!.day}/${order.createdAt!.month}/${order.createdAt!.year}'
        : 'Today';

    return Container(
      decoration: AppTheme.luxuryCardDecoration,
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                '#${order.orderReference}',
                style: const TextStyle(
                  fontSize: 16,
                  fontWeight: FontWeight.w900,
                  color: AppTheme.primaryNavy,
                ),
              ),
              Text(
                'Date: $createdDateStr',
                style: const TextStyle(fontSize: 12, color: AppTheme.textSubtle),
              ),
            ],
          ),
          const Divider(height: 20),
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Icon(Icons.location_on_outlined, size: 18, color: AppTheme.primaryNavy),
              const SizedBox(width: 6),
              Expanded(
                child: Text(
                  'Delivery Address: ${order.deliveryAddress.isNotEmpty ? order.deliveryAddress : 'Site Address'}',
                  style: const TextStyle(fontSize: 12, color: AppTheme.textDark, fontWeight: FontWeight.w500),
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('Total Boxes', style: TextStyle(fontSize: 11, color: AppTheme.textSubtle)),
                  Text('${order.totalBoxes} Boxes', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 13)),
                ],
              ),
              Column(
                crossAxisAlignment: CrossAxisAlignment.end,
                children: [
                  const Text('Total Weight (Tonnes)', style: TextStyle(fontSize: 11, color: AppTheme.textSubtle)),
                  Text('${order.totalWeightTons.toStringAsFixed(2)} Tonnes', style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 13)),
                ],
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildItemsTable(TileOrder order, bool isPendingRate) {
    return Container(
      decoration: AppTheme.luxuryCardDecoration,
      child: ListView.separated(
        shrinkWrap: true,
        physics: const NeverScrollableScrollPhysics(),
        itemCount: order.items.length,
        separatorBuilder: (_, _) => const Divider(height: 1, color: AppTheme.borderSubtle),
        itemBuilder: (context, index) {
          final item = order.items[index];

          return Padding(
            padding: const EdgeInsets.all(12),
            child: Row(
              children: [
                Container(
                  width: 44,
                  height: 44,
                  decoration: BoxDecoration(
                    color: AppTheme.primaryNavy.withValues(alpha: 0.08),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Icon(Icons.terrain_rounded, color: AppTheme.primaryNavy, size: 22),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        item.productName,
                        style: const TextStyle(
                          fontSize: 13,
                          fontWeight: FontWeight.bold,
                          color: AppTheme.textDark,
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        '${item.size} • ${item.surface} • ${item.quantityBoxes} Boxes (${item.quantitySqFt.toStringAsFixed(1)} sq.ft)',
                        style: const TextStyle(fontSize: 11, color: AppTheme.textSubtle),
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 8),
                if (isPendingRate)
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                    decoration: BoxDecoration(
                      color: AppTheme.accentOrange.withValues(alpha: 0.15),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: const Text(
                      'Rate Approval in Progress',
                      style: TextStyle(
                        fontSize: 10,
                        fontWeight: FontWeight.bold,
                        color: AppTheme.accentOrange,
                      ),
                    ),
                  )
                else
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.end,
                    children: [
                      Text(
                        '₹${(item.unitPrice ?? 0.0).toStringAsFixed(2)}/sq.ft',
                        style: const TextStyle(
                          fontSize: 12,
                          fontWeight: FontWeight.w700,
                          color: AppTheme.accentOrange,
                        ),
                      ),
                      Text(
                        'Total: ₹${(item.lineTotal ?? (item.quantitySqFt * (item.unitPrice ?? 0.0))).toStringAsFixed(2)}',
                        style: const TextStyle(
                          fontSize: 11,
                          fontWeight: FontWeight.bold,
                          color: AppTheme.primaryNavy,
                        ),
                      ),
                    ],
                  ),
              ],
            ),
          );
        },
      ),
    );
  }

  Widget _buildFinancialSummaryCard(TileOrder order) {
    return Container(
      decoration: AppTheme.luxuryCardDecoration,
      padding: const EdgeInsets.all(16),
      child: Column(
        children: [
          _buildSummaryRow('Subtotal', order.subtotal),
          if (order.discount > 0)
            _buildSummaryRow('Discount (Applied)', -order.discount, isDiscount: true),
          _buildSummaryRow('18% GST (Tax)', order.taxAmount),
          const Divider(height: 20),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Final Total Amount',
                style: TextStyle(
                  fontSize: 15,
                  fontWeight: FontWeight.w900,
                  color: AppTheme.primaryNavy,
                ),
              ),
              Text(
                '₹${order.totalAmount.toStringAsFixed(2)}',
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w900,
                  color: AppTheme.accentOrange,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildSummaryRow(String label, double amount, {bool isDiscount = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: const TextStyle(fontSize: 13, color: AppTheme.textSubtle)),
          Text(
            '${isDiscount ? '-' : ''}₹${amount.abs().toStringAsFixed(2)}',
            style: TextStyle(
              fontSize: 13,
              fontWeight: FontWeight.w600,
              color: isDiscount ? AppTheme.statusSuccess : AppTheme.textDark,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildDynamicActionBlock(
    TileOrder order,
    bool isPendingRate,
    bool isRateQuoted,
    bool isConfirmed,
    bool isRejected,
  ) {
    if (isPendingRate) {
      return Container(
        width: double.infinity,
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: AppTheme.borderSubtle),
        ),
        child: const Text(
          'Your assigned salesperson is currently quoting today\'s factory rates. You will be notified once ready.',
          textAlign: TextAlign.center,
          style: TextStyle(fontSize: 13, color: AppTheme.textSubtle, fontWeight: FontWeight.w500),
        ),
      );
    }

    if (isRateQuoted) {
      return Column(
        children: [
          Container(
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: AppTheme.borderSubtle),
            ),
            child: CheckboxListTile(
              value: _isConfirmed,
              activeColor: AppTheme.primaryNavy,
              title: const Text(
                'I agree with today\'s quoted rates and terms for this Purchase Order.',
                style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600),
              ),
              onChanged: (val) => setState(() => _isConfirmed = val ?? false),
            ),
          ),
          const SizedBox(height: 16),
          SizedBox(
            width: double.infinity,
            child: ElevatedButton(
              style: ElevatedButton.styleFrom(
                backgroundColor: _isConfirmed ? AppTheme.primaryNavy : Colors.grey.shade400,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
              ),
              onPressed: _isConfirmed && !_isSubmitting ? () => _handleConfirmOrder(order) : null,
              child: _isSubmitting
                  ? const CircularProgressIndicator(color: Colors.white)
                  : const Text(
                      'Confirm & Finalize Order →',
                      style: TextStyle(
                        fontSize: 15,
                        fontWeight: FontWeight.bold,
                        letterSpacing: 0.5,
                      ),
                    ),
            ),
          ),
          const SizedBox(height: 10),
          SizedBox(
            width: double.infinity,
            child: OutlinedButton(
              style: OutlinedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 14),
                side: const BorderSide(color: AppTheme.statusError),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
              ),
              onPressed: !_isSubmitting ? () => _handleRejectOrder(order) : null,
              child: const Text(
                'Reject Estimate',
                style: TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.bold,
                  color: AppTheme.statusError,
                ),
              ),
            ),
          ),
        ],
      );
    }

    if (isConfirmed) {
      return Column(
        children: [
          Container(
            width: double.infinity,
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: AppTheme.statusSuccess.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(8),
            ),
            child: const Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(Icons.check_circle_rounded, color: AppTheme.statusSuccess, size: 20),
                SizedBox(width: 8),
                Text(
                  'Order Confirmed',
                  style: TextStyle(fontSize: 13, fontWeight: FontWeight.bold, color: AppTheme.statusSuccess),
                ),
              ],
            ),
          ),
          const SizedBox(height: 14),
          SizedBox(
            width: double.infinity,
            child: ElevatedButton.icon(
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.primaryNavy,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
              ),
              icon: const Icon(Icons.picture_as_pdf_rounded, color: Colors.white),
              label: const Text(
                'Download Official PO (PDF)',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 0.5,
                ),
              ),
              onPressed: () => _handleDownloadPdf(order.poDocumentUrl),
            ),
          ),
        ],
      );
    }

    return Container();
  }
}
